# -*- coding: utf-8 -*-
"""mlproje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6s8qmwwhpeUH_WFujX7CGMLF00V2bsH

#  Orman Yangını Şiddeti Tahmini Projesi 🌳🔥

##  1. VERİ YÜKLEME VE İNCELEME
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

try:
  df = pd.read_csv("/content/drive/MyDrive/forestfires.csv")
except:
  # İsterseniz drive bağlamak yerine soldaki klasörü açıp veri setini oraya sürükleyebilirsiniz.
  # Kod böyle de çalışır.
  df = pd.read_csv('forestfires.csv')
print(df)

#from google.colab import drive
#drive.mount('/content/drive')

# Already loaded above with local fallback.
# df = pd.read_csv('/content/drive/MyDrive/forestfires.csv')

"""## 2. GÖRSELLEŞTİRME (EDA) YUSUF DİLER'İN KISMI"""

# İlk 5 satır
df.head()

# Verinin temel istatistikleri
print("Veri Seti İstatistiksel Özeti:")
print(df.describe())


print("\nEksik Değer Kontrolü:")
print(df.isnull().sum())

plt.figure(figsize=(12, 5))

# Sol grafik: Orijinal dağılım
plt.subplot(1, 2, 1)
sns.histplot(df['area'], kde=True, color='orange')
plt.title('Orijinal Yangın Alanı Dağılımı')

# Sağ grafik: Log dönüşümü uygulanmış dağılım
plt.subplot(1, 2, 2)
# np.log1p kullanıyoruz çünkü 0 değerleri için hata almamalıyız (ln(x+1))
sns.histplot(np.log1p(df['area']), kde=True, color='green')
plt.title('Logaritmik Dönüşüm Sonrası Dağılım')

plt.show()

# Korelasyon Isı Haritası
plt.figure(figsize=(10, 8))
correlation_matrix = df.select_dtypes(include=[np.number]).corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Hava Koşulları ve Değişkenler Arası Korelasyon')
plt.show()

# En güçlü ilişki: Sıcaklık vs Yangın Alanı (Log)
df['log_area'] = np.log1p(df['area'])
plt.figure(figsize=(8, 5))
sns.scatterplot(x='temp', y='log_area', data=df, alpha=0.5)
plt.title('Sıcaklık ve Yangın Alanı Arasındaki İlişki')
plt.xlabel('Sıcaklık (C)')
plt.ylabel('Yanan Alan (Log)')
plt.show()

# Daha iyi bir Box Plot görüntüsü için Logaritmik Ölçek
plt.figure(figsize=(10, 5))
sns.boxplot(x=np.log1p(df['area']), color='cyan')
plt.title('Yangın Alanı Dağılımı (Log Ölçekli - Daha Net Görünüm)')
plt.xlabel('Log(Area + 1)')
plt.show()

# Spesifik korelasyon analizi
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# Sıcaklık vs Alan
sns.regplot(x='temp', y='log_area', data=df, ax=axes[0], color='red', scatter_kws={'alpha':0.3})
axes[0].set_title('Sıcaklık - Yangın Alanı İlişkisi')

# Nem vs Alan
sns.regplot(x='RH', y='log_area', data=df, ax=axes[1], color='blue', scatter_kws={'alpha':0.3})
axes[1].set_title('Nem - Yangın Alanı İlişkisi')

# Rüzgar vs Alan
sns.regplot(x='wind', y='log_area', data=df, ax=axes[2], color='green', scatter_kws={'alpha':0.3})
axes[2].set_title('Rüzgar - Yangın Alanı İlişkisi')

plt.show()

"""## 3. VERİ ÖN İŞLEME VE ÖZNİTELİK MÜHENDİSLİĞİ (EREN)"""

# Hedef değişken 'area' veri seti çok çarpık olduğu için
# logaritmik ölçeğe çevirilir.
df['log_area'] = np.log1p(df['area'])

# Sıcaklık / Nem oranı (Sıcaklık arttıkça ve nem düştükçe bu değer büyür)
df['temp_RH_ratio'] = df['temp'] / (df['RH'] + 1)

plt.figure(figsize=(10, 6))
sns.regplot(x='temp_RH_ratio', y='log_area', data=df,
            scatter_kws={'alpha':0.5, 'color':'orange'},
            line_kws={'color':'red'})

plt.title('Sıcaklık/Nem Oranı vs. Yanan Alan (Log)')
plt.xlabel('Sıcaklık / Nem Oranı')
plt.ylabel('Yanan Alan (log(area+1))')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""Bu grafikte y=0 hattında çok fazla veri noktası var. Bunlar "Yangın çıktı ama YAYILMADI" anlamına gelirler.

Grafikte sağa doğru gidildikçe (oran arttıkça) noktaların yukarı-aşağı yayılımının arttığı görülüyor. Bu, risk arttıkça sonucun daha öngörülemez hale geldiğini gösterir.
"""

# Topraktaki nem ve kuraklık indekslerini toplayarak genel kuraklık indeksi oluşturma
df['drought_index'] = df['DMC'] + df['DC']

plt.figure(figsize=(10, 6))
sns.regplot(x='drought_index', y='log_area', data=df,
            scatter_kws={'alpha':0.5, 'color':'teal'},
            line_kws={'color':'darkred'})

plt.title('Kuraklık İndeksi vs. Yanan Alan (Log)')
plt.xlabel('Kuraklık İndeksi (DMC + DC)')
plt.ylabel('Yanan Alan (log(area+1))')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""Yüksek kuraklık büyük bir yangın için gerekli bir şarttır ama yeterli değildir. Büyük bir yangın için hem kuraklık, hem rüzgar, hem de bir ateşleme (izmarit, yıldırım vb.) aynı anda gerçekleşmelidir. y=0 hattında yine yangınlar büyümeden sönmüş, burada insan müdahalesi(itfaiye) muhtemeldir."""

# Rüzgar hızı ile yayılım indeksinin çarpımı
df['wind_ISI_impact'] = df['wind'] * df['ISI']

plt.figure(figsize=(10, 6))
sns.regplot(x='wind_ISI_impact', y='log_area', data=df,
            scatter_kws={'alpha':0.5, 'color':'red'},
            line_kws={'color':'darkred'})

plt.title('Rüzgar Yayılım Hızı vs. Yanan Alan (Log)')
plt.xlabel('Rüzgar Yayılım Hızı (Wind_ISI)')
plt.ylabel('Yanan Alan (log(area+1))')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# 30 derece üstü çok riskli (1), altı daha az riskli (0)
df['high_temp_risk'] = (df['temp'] > 30).astype(int)

plt.figure(figsize=(10, 6))
sns.regplot(x='high_temp_risk', y='log_area', data=df,
            scatter_kws={'alpha':0.5, 'color':'orange'},
            line_kws={'color':'darkred'})

plt.title('30 derece üstü sıcaklık vs. Yanan Alan (Log)')
plt.xlabel('30 derece üstü sıcaklık')
plt.ylabel('Yanan Alan (log(area+1))')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""Genelde hava 30 dereceyi
geçtiğinde orman girişleri yasaklanır ve gözetleme kuleleri maksimum alarma geçer. Bu yüzden yangın çıksa bile çok hızlı söndürüldüğü için alan 0 kalır.
"""

# Ağustos ve Eylül ayları veri setinde yangınların en yoğun olduğu aylardır
# Bu ayları yaz ayı olarak kabul edip is_summer sütunu olarak ekleyeceğiz.
df['is_summer'] = df['month'].apply(lambda x: 1 if x in ['aug', 'sep'] else 0)

plt.figure(figsize=(10, 6))
sns.regplot(x='is_summer', y='log_area', data=df,
            scatter_kws={'alpha':0.5, 'color':'orange'},
            line_kws={'color':'darkred'})

plt.title('Yaz Ayları vs. Yanan Alan (Log)')
plt.xlabel('Yaz Ayları')
plt.ylabel('Yanan Alan (log(area+1))')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""Yangınların büyük bir çoğunluğu ve en geniş alanlı olanları Ağustos ve Eylül aylarında kümelenmiştir. Bu da mevsimselliğin yangın şiddeti üzerindeki baskın etkisini kanıtlar.

Regresyon çizgisinin pozitif eğimi, is_summer değişkeni ile log_area arasında pozitif bir korelasyon olduğunu gösterir. Yani 'Yaz Mevsimi' durumu, yangın alanının büyüme olasılığını istatistiksel olarak artırmaktadır.

Yaz aylarında yangınların sadece sayısı artmamakta, aynı zamanda kontrol edilemez hale gelip büyük alanlara yayılma varyansı da yükselmektedir. Diğer aylarda büyük yangın çıkma ihtimali çok daha düşüktür
"""

# One-Hot Encoding
# 'month' ve 'day' sütunlarını One-Hot Encoding ile sayısal yapalım
df_final = pd.get_dummies(df, columns=['month', 'day'])

# Veri setinin yeni hali
print(df_final.head())

# Sadece orijinal 'area' sütununu çıkarıyoruz.
if 'area' in df_final.columns:
    df_final = df_final.drop('area', axis=1)

# --- SON KONTROL VE KAYDETME ---
print("Veri Hazırlama Tamamlandı!")
print(f"Veri Seti Boyutu: {df_final.shape}")
print("-" * 30)
print("Yeni Eklenen Sütunların Kontrolü:")
print(df_final[['log_area', 'wind_ISI_impact', 'high_temp_risk', 'is_summer']].head())

# CSV olarak kaydet (index=False fazladan numara sütunu oluşmasını engeller.)
df_final.to_csv('forestfires_processed.csv', index=False)

"""# 4. MODEL OLUŞTURMA(Sınıflandırma için güncellendi)"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn kütüphaneleri
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Modeller
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

# ---------------------------------------------------------
# 1. VERİYİ YÜKLEME
# ---------------------------------------------------------
# Buraya kendi işlenmiş veri setinizin adını yazın
df = pd.read_csv('forestfires_processed.csv')

# ---------------------------------------------------------
# 2. HEDEF DEĞİŞKENİ OLUŞTURMA (Label Encoding)
# ---------------------------------------------------------
# Senaryo A: Hiç yangın yok (0) vs Yangın Var (1)
# Eğer 'log_area' sütunu (veya area) 0'dan büyükse 1, değilse 0 olsun.
df['label'] = df['log_area'].apply(lambda x: 1 if x > 0 else 0)

print(f"Sınıf Dağılımı:\n{df['label'].value_counts()}")
print("-" * 30)

# ---------------------------------------------------------
# 3. VERİ HAZIRLIĞI VE ÖLÇEKLENDİRME (SCALING)
# ---------------------------------------------------------
# Hedef değişkeni (label) ve sızıntı yapabilecek orijinal sütunları çıkarıyoruz.
X = df.drop(['log_area', 'label'], axis=1) # 'area' sütunu varsa onu da buraya ekleyip çıkarın
y = df['label']

# Eğitim ve Test ayırma (%80 Eğitim, %20 Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# !!! KRİTİK ADIM: SVC ve KNN için veriyi standartlaştırma !!!
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ---------------------------------------------------------
# 4. MODELLERİN TANIMLANMASI VE DÖNGÜ
# ---------------------------------------------------------
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "Support Vector Machine (SVC)": SVC(kernel='rbf', random_state=42),
    "K-Nearest Neighbors (KNN)": KNeighborsClassifier(n_neighbors=5),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

results = {} # Sonuçları saklamak için sözlük

print("\n=== MODELLER EĞİTİLİYOR VE TEST EDİLİYOR ===\n")

for name, model in models.items():
    # SVC, KNN ve Logistic Reg. için ölçeklenmiş veriyi kullanmak daha iyidir
    if name in ["Support Vector Machine (SVC)", "K-Nearest Neighbors (KNN)", "Logistic Regression"]:
        current_X_train = X_train_scaled
        current_X_test = X_test_scaled
    else:
        # Ağaç tabanlı modeller (RF, GBM) ölçekleme gerektirmez ama ölçekli veriyle de çalışır.
        # Yine de orijinali verelim:
        current_X_train = X_train
        current_X_test = X_test

    # Modeli eğit
    model.fit(current_X_train, y_train)

    # Tahmin yap
    y_pred = model.predict(current_X_test)

    # Başarı skorunu hesapla
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

    print(f"--> {name} Modeli Tamamlandı.")
    print(f"    Doğruluk (Accuracy): {acc:.4f}")
    print("-" * 30)

# ---------------------------------------------------------
# 5. EN İYİ MODELİ BULMA VE RAPORLAMA
# ---------------------------------------------------------
best_model_name = max(results, key=results.get)
best_acc = results[best_model_name]

print(f"\n🏆 EN İYİ MODEL: {best_model_name}")
print(f"🏆 BAŞARI ORANI: {best_acc:.4f}\n")

# En iyi modelin detaylı raporunu tekrar yazdıralım
print(f"=== {best_model_name} İçin Detaylı Rapor ===")

# En iyi modeli tekrar çağırıp (veya dictionary'den alıp) detayları basıyoruz
best_model = models[best_model_name]
if best_model_name in ["Support Vector Machine (SVC)", "K-Nearest Neighbors (KNN)", "Logistic Regression"]:
    final_pred = best_model.predict(X_test_scaled)
else:
    final_pred = best_model.predict(X_test)

print(classification_report(y_test, final_pred))
print("Karmaşıklık Matrisi (Confusion Matrix):")
cm = confusion_matrix(y_test, final_pred)
print(cm)

# ---------------------------------------------------------
# EKSTRA: Eğer en iyi model Ağaç tabanlıysa Öznitelik Önemini göster
# ---------------------------------------------------------
if hasattr(best_model, 'feature_importances_'):
    feature_imp = pd.Series(best_model.feature_importances_, index=X.columns).sort_values(ascending=False)
    print("\nEn Önemli 5 Özellik (Feature Importances):")
    print(feature_imp.head(5))
else:
    print(f"\nNot: '{best_model_name}' modeli 'feature_importances_' özniteliğini desteklemiyor (Örn: SVC veya KNN).")

"""# Soncucu Görselleştirme"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, roc_curve, auc

# --- Ön Hazırlık ---
# En iyi modelimiz Random Forest idi
y_pred = best_model.predict(X_test)
y_pred_proba = best_model.predict_proba(X_test)[:, 1] # ROC eğrisi için olasılık değerleri

# Grafik Alanı Oluşturma (1 Satır, 3 Sütun)
fig, ax = plt.subplots(1, 3, figsize=(20, 5))

# --- GRAFİK 1: Karmaşıklık Matrisi (Confusion Matrix) ---
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax[0], cbar=False,
            xticklabels=['Yangın Yok', 'Yangın Var'],
            yticklabels=['Yangın Yok', 'Yangın Var'])
ax[0].set_title('Karmaşıklık Matrisi (Confusion Matrix)')
ax[0].set_xlabel('Tahmin Edilen')
ax[0].set_ylabel('Gerçek Durum')

# --- GRAFİK 2: ROC Eğrisi ---
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

ax[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC Eğrisi (AUC = {roc_auc:.2f})')
ax[1].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
ax[1].set_xlim([0.0, 1.0])
ax[1].set_ylim([0.0, 1.05])
ax[1].set_xlabel('False Positive Rate (Yanlış Alarm)')
ax[1].set_ylabel('True Positive Rate (Doğru Tespit)')
ax[1].set_title('ROC - Receiver Operating Characteristic')
ax[1].legend(loc="lower right")

# --- GRAFİK 3: Özellik Önem Düzeyleri (Feature Importance) ---
importances = best_model.feature_importances_
indices = np.argsort(importances)[::-1]
top_n = 7 # En önemli 7 özelliği gösterelim

ax[2].bar(range(top_n), importances[indices][:top_n], align="center", color='salmon')
ax[2].set_xticks(range(top_n))
ax[2].set_xticklabels(X.columns[indices][:top_n], rotation=45)
ax[2].set_title('Model İçin En Önemli Özellikler')
ax[2].set_xlabel('Özellikler')
ax[2].set_ylabel('Önem Skoru')

plt.tight_layout()
plt.show()

"""# Proje Sonuçları ve Değerlendirme
1. Çalışmanın Özeti
Bu projede, UCI Machine Learning Repository'den alınan Forest Fires veri seti kullanılarak orman yangınlarının oluşup oluşmayacağını (veya yangının şiddetini) tahmin eden bir makine öğrenmesi hattı (pipeline) geliştirilmiştir.

Süreç boyunca aşağıdaki adımlar izlenmiştir:

Veri Ön İşleme: Eksik verilerin kontrolü, aykırı değerlerin incelenmesi.

Öznitelik Mühendisliği (Feature Engineering): log_area dönüşümü ve kategorik verilerin sayısal hale getirilmesi.

Modelleme: Random Forest, SVC, KNN, Logistic Regression ve Gradient Boosting modelleri eğitilmiş ve kıyaslanmıştır.

2. Model Performansı
Yapılan deneyler sonucunda en yüksek başarıyı Random Forest algoritması göstermiştir.

Doğruluk (Accuracy): %60

En Önemli Özellikler: Modelin karar verirken en çok dikkate aldığı değişkenler, yukarıdaki grafiklerde de görüldüğü üzere meteorolojik veriler (sıcaklık, rüzgar, nem) ve tarihsel indeksler (FFMC, DMC) olmuştur.

3. Sonuçların Yorumlanması
Elde edilen %60 doğruluk oranı, literatürdeki benzer çalışmalarla tutarlılık göstermektedir. Bu oranın daha yüksek çıkmamasının temel nedenleri şunlardır:

Veri Setinin Doğası: Orman yangınları sadece meteorolojik verilere (sıcaklık, nem vb.) bağlı değildir; insan faktörü, bitki örtüsü türü ve topografya gibi veri setinde bulunmayan dış etkenler de büyük rol oynar.

Dengesiz Dağılım: Veri setinde "yangın olmayan" veya "çok küçük yangın" olan günlerin sayısı, büyük yangınlara göre daha fazladır.

Gürültülü Veri: Küçük yangınların meteorolojik verileri ile yangın olmayan günlerin verileri birbirine çok yakındır, bu da modelin ayrım yapmasını zorlaştırmaktadır.

# Regresyon Modelleri
"""

X = df_final.drop(['log_area'], axis=1)
y = df_final['log_area'] # Hedef olarak logaritmik alanı kullanıyoruz

# ---------------------------------------------------------
# 2. KORELASYON ANALİZİ VE TEMİZLİK
# ---------------------------------------------------------
# Amacımız: Birbiriyle çok yüksek ilişkiye sahip (korelasyon > 0.85) değişkenlerden
# birini eleyerek modelin karmaşıklığını azaltmak ve overfitting'i önlemek.

# Korelasyon matrisini hesapla (Mutlak değer)
corr_matrix = X.corr(numeric_only=True).abs()

# Matrisin üst üçgenini seç (Aynı ikilileri tekrar etmemek için)
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# %85'ten yüksek korelasyona sahip sütunları bul
to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]

print(f"Yüksek korelasyon nedeniyle çıkarılan değişkenler: {to_drop}")

# Belirlenen sütunları veri setinden çıkar
X = X.drop(columns=to_drop)

# ---------------------------------------------------------
# 3. VERİ SETİNİ BÖLME VE ÖLÇEKLENDİRME
# ---------------------------------------------------------
# Veriyi %80 Eğitim, %20 Test olarak ayır
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Veriyi ölçeklendir (Standard Scaling)
# Sütun isimlerini korumak için DataFrame'e geri çeviriyoruz
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns)

# ---------------------------------------------------------
# 4. MODELLEME VE HİPERPARAMETRE OPTİMİZASYONU (GridSearch)
# ---------------------------------------------------------
# Denenecek modeller ve optimize edilecek parametre aralıkları

models_params = {
    'Linear Regression': {
        'model': LinearRegression(),
        'params': {}
    },
    'Random Forest': {
        'model': RandomForestRegressor(random_state=42),
        'params': {
            'n_estimators': [100, 200],
            'max_depth': [10, 20, None],
            'min_samples_leaf': [1, 2, 4]
        }
    },
    'SVR': {
        'model': SVR(),
        'params': {
            'kernel': ['rbf', 'linear'], # Çekirdek fonksiyonu
            'C': [1, 10],
            'epsilon': [0.1, 0.5]
        }
    },
    'XGBoost': {
        'model': XGBRegressor(objective='reg:squarederror', random_state=42),
        'params': {
            'n_estimators': [100, 200],    # Ağaç sayısı
            'learning_rate': [0.01, 0.1],  # Öğrenme hızı (Daha küçük = daha dikkatli)
            'max_depth': [3, 5]            # Ağaç derinliği
        }
    }
}

results = []

print("\nModeller eğitiliyor ve optimize ediliyor (Bu işlem biraz sürebilir)...")

for model_name, mp in models_params.items():
    # GridSearch: En iyi parametreleri bulmak için çapraz doğrulama (CV=5) yapar
    clf = GridSearchCV(mp['model'], mp['params'], cv=5,
                       scoring='neg_mean_squared_error', n_jobs=-1)

    # Modeli eğit
    clf.fit(X_train_scaled, y_train)

    # En iyi model ile test seti üzerinde tahmin yap
    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test_scaled)

    # Başarı metriklerini hesapla
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    results.append({
        'Model': model_name,
        'Best Params': str(clf.best_params_) if mp['params'] else "Default",
        'MAE': mae,
        'RMSE': rmse,
        'R2 Score': r2
    })

# ---------------------------------------------------------
# 5. SONUÇLARIN RAPORLANMASI
# ---------------------------------------------------------
results_df = pd.DataFrame(results)

print("\n" + "="*80)
print("MODEL PERFORMANS TABLOSU (Hedef: Log Area)")
print("="*80)
print(results_df[['Model', 'MAE', 'RMSE', 'R2 Score']])

# En başarılı modeli seç (RMSE değeri en düşük olan)
best_model_row = results_df.loc[results_df['RMSE'].idxmin()]

print("\n" + "-"*80)
print(f"EN BAŞARILI MODEL: {best_model_row['Model']}")
print(f"En Düşük Hata (RMSE): {best_model_row['RMSE']:.4f}")
print(f"En İyi Parametreler: {best_model_row['Best Params']}")
print("-"*80)

"""# Sonuç"""

# 1. En iyi parametrelerle Final Modeli Kuruyoruz
final_model = XGBRegressor(
    objective='reg:squarederror',
    learning_rate=0.01,      # GridSearch'ten gelen en iyi değerler
    max_depth=3,
    n_estimators=100,
    random_state=42
)

# 2. Modeli Eğitiyoruz
final_model.fit(X_train_scaled, y_train)

# 3. Tahmin Yapıyoruz
y_pred_final = final_model.predict(X_test_scaled)

# 4. "Gerçek vs Tahmin" Grafiğini Çiziyoruz
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_final, alpha=0.5, color='teal', label='Tahminler')

# Mükemmel tahmin çizgisini (y=x) ekliyoruz(Kırmızı Çizgi)
# Bu çizgiye ne kadar yakınlarsa o kadar iyi
min_val = min(y_test.min(), y_pred_final.min())
max_val = max(y_test.max(), y_pred_final.max())
plt.plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--', lw=2, label='Mükemmel Tahmin')

plt.title('XGBoost Başarısı: Gerçek Değerler vs. Tahminler', fontsize=14)
plt.xlabel('Gerçek Yanan Alan (Log)', fontsize=12)
plt.ylabel('Tahmin Edilen Yanan Alan (Log)', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""# Öznitelik Önem Düzeyi"""

# 1. En iyi parametrelerle XGBoost'u tekrar tanımlıyoruz
best_xgb = XGBRegressor(
    objective='reg:squarederror',
    n_estimators=100,        # Çıktıdaki en iyi değer
    learning_rate=0.01,      # Çıktıdaki en iyi değer
    max_depth=3,             # Çıktıdaki en iyi değer
    random_state=42
)

# 2. Model eğitimi
best_xgb.fit(X_train_scaled, y_train)

# 3. Hangi özelliğin ne kadar önemli olduğunu çekiyoruz
feature_importances = pd.DataFrame({
    'Feature': X_train_scaled.columns,
    'Importance': best_xgb.feature_importances_
}).sort_values(by='Importance', ascending=False)

# 4. Görselleştirme (Bar Plot)
plt.figure(figsize=(10, 8))
sns.barplot(x='Importance', y='Feature', data=feature_importances.head(15), palette='viridis')
plt.title('XGBoost Modeline Göre En Önemli Yangın Göstergeleri')
plt.xlabel('Önem Düzeyi')
plt.ylabel('Öznitelikler')
plt.show()

# Tablo olarak
print("\nEn Önemli 10 Özellik:")
print(feature_importances.head(10))

